### ISSUE TITLE
🎨 [UI] Implement authentication page design

### ISSUE THREAD

**Issue by njokuScript** [LazerPay-Finance/Lazerpay-documentation-v2#12]
**Please describe the UI Improvement request**
Currently, there's no UI implementation for the authentication page of the documentation. 
We need to implement the UI design for the authentication section. The design is shown in the Figma URL below

**Does this solution have a Figma design URL attached to it? paste it here (optional)**
[Figma URL](https://www.figma.com/file/MocT7avQcyofsHa1pujaLD/Lazerpay-Documentation?node-id=2133%3A66802)

**Comment by Khadeeejah** [comment]
i would like to work on this @MeisterJustice

**Comment by MeisterJustice** [comment]
> i would like to work on this @MeisterJustice

Cool 😎 🙅🏾‍♂️
