### ISSUE TITLE
🎨 [UI] Implement Payments get started page.

### ISSUE THREAD

**Issue by njokuScript** [LazerPay-Finance/Lazerpay-documentation-v2#13]
**Please describe the improvement request**
Currently, there's no UI implementation for the payments get started page of the documentation. 
We need to implement the design for the authentication page of the documentation. The design is shown in the Figma URL below

**Does this solution have a Figma design URL attached to it? paste it here (optional)**
[Figma URL](https://www.figma.com/file/MocT7avQcyofsHa1pujaLD/Lazerpay-Documentation?node-id=2133%3A69368)

**Comment by asapconet** [comment]
May I hoop on this already ?

**Comment by Frontend-io** [comment]
Yes please  @asapconet
