### ISSUE TITLE
🎨 [UI] Implement Transfers > get started page

### ISSUE THREAD

**Issue by MeisterJustice** [LazerPay-Finance/Lazerpay-documentation-v2#19]
**Please describe the improvement request**
The transfers API allows developers to programmatically make fast, global payouts to customers, vendors, and suppliers using traditional bank wires, or making native crypto transfers.

**Describe the solution you'd like**
Code the design and functionalities of the transfers > get started page.

**Does this solution have a figma design url attached to it? paste it here (optional)**
[Figma URL](https://www.figma.com/file/MocT7avQcyofsHa1pujaLD/Lazerpay-Documentation?node-id=2133%3A98771)

**Comment by gzkdev** [comment]
Hi, can I work on this?

**Comment by MeisterJustice** [comment]
I think someone else is already on it. You can pick another please? or still proceed with this one if you want

**Comment by gzkdev** [comment]
@MeisterJustice Alright, I'll pick another one
