### ISSUE TITLE
🎨 [UI] Implement Transfers > Bank Transfers

### ISSUE THREAD

**Issue by MeisterJustice** [LazerPay-Finance/Lazerpay-documentation-v2#27]
**Please describe the improvement request**
Developers can payout crypto to bank accounts using the Lazerpay API

**Describe the solution you'd like**
Design and implement the page that explains how devs can use the Lazerpay API to programmatically withdraw crypto to a bank account

**Does this solution have a figma design url attached to it? paste it here (optional)**
[Figma URL](https://www.figma.com/file/MocT7avQcyofsHa1pujaLD/Lazerpay-Documentation?node-id=2133%3A103165)

**Comment by asapconet** [comment]
May I? 😇

**Comment by MeisterJustice** [comment]
> May I? 😇

you may 😁
